<?php
defined('_JEXEC') or die;
use Joomla\CMS\Language\Text;
?>
<div class="xdecaro-scope xdd-draw">
  <div class="xdd-info-grid">
    <section class="xdecaro-card"><div class="xdecaro-card__header"><h2 class="xdecaro-card__title"><?php echo Text::_('COM_XDECARODRAW_INFO_PRODUCT'); ?></h2></div><div class="xdecaro-card__body"><dl class="xdd-details"><dt><?php echo Text::_('COM_XDECARODRAW_VERSION'); ?></dt><dd><?php echo $this->escape($this->version); ?></dd><dt><?php echo Text::_('COM_XDECARODRAW_TECHNICAL_ID'); ?></dt><dd><code>com_xdecarodraw</code></dd><dt><?php echo Text::_('COM_XDECARODRAW_ALGORITHM'); ?></dt><dd><code>1.0.0</code></dd></dl></div></section>
    <section class="xdecaro-card"><div class="xdecaro-card__header"><h2 class="xdecaro-card__title"><?php echo Text::_('COM_XDECARODRAW_INFO_ENVIRONMENT'); ?></h2></div><div class="xdecaro-card__body"><dl class="xdd-details"><dt>Joomla</dt><dd><?php echo $this->escape(JVERSION); ?></dd><dt>PHP</dt><dd><?php echo $this->escape(PHP_VERSION); ?></dd><dt><?php echo Text::_('COM_XDECARODRAW_CORE'); ?></dt><dd><?php echo $this->coreVersion !== '' ? $this->escape($this->coreVersion) : Text::_('COM_XDECARODRAW_NOT_INSTALLED'); ?></dd></dl></div></section>
    <section class="xdecaro-card"><div class="xdecaro-card__header"><h2 class="xdecaro-card__title"><?php echo Text::_('COM_XDECARODRAW_INFO_INCLUDED'); ?></h2></div><div class="xdecaro-card__body"><dl class="xdd-details"><dt>Component</dt><dd><span class="xdd-status xdd-status--published">com_xdecarodraw</span></dd><dt>Package</dt><dd><span class="xdd-status xdd-status--published">pkg_xdecarodraw</span></dd></dl></div></section>
    <section class="xdecaro-card"><div class="xdecaro-card__header"><h2 class="xdecaro-card__title"><?php echo Text::_('COM_XDECARODRAW_INFO_UPDATES'); ?></h2></div><div class="xdecaro-card__body"><dl class="xdd-details"><dt><?php echo Text::_('COM_XDECARODRAW_UPDATE_SERVER'); ?></dt><dd>GitHub</dd><dt>Semantic Versioning</dt><dd><span class="xdd-status xdd-status--published"><?php echo Text::_('COM_XDECARODRAW_CONFIGURED'); ?></span></dd></dl></div></section>
  </div>
  <section class="xdecaro-card xdd-panel"><div class="xdecaro-card__header"><h2 class="xdecaro-card__title"><?php echo Text::_('COM_XDECARODRAW_INFO_CONNECTED'); ?></h2></div><div class="xdecaro-card__body"><div class="xdd-connections"><div><strong>Core</strong><span class="xdd-status <?php echo $this->coreCapabilityAvailable ? 'xdd-status--published' : ''; ?>"><?php echo $this->coreCapabilityAvailable ? Text::_('COM_XDECARODRAW_AVAILABLE') : Text::_('COM_XDECARODRAW_OPTIONAL'); ?></span><small><?php echo Text::_('COM_XDECARODRAW_CORE_CONNECTION_DESC'); ?></small></div><div><strong>Competitions</strong><span class="xdd-status <?php echo $this->competitionsInstalled ? 'xdd-status--published' : ''; ?>"><?php echo $this->competitionsInstalled ? Text::_('COM_XDECARODRAW_INSTALLED') : Text::_('COM_XDECARODRAW_OPTIONAL'); ?></span><small><?php echo Text::_('COM_XDECARODRAW_COMPETITIONS_CONNECTION_DESC'); ?></small></div></div></div></section>
  <section class="xdecaro-card xdd-panel"><div class="xdecaro-card__header"><h2 class="xdecaro-card__title"><?php echo Text::_('COM_XDECARODRAW_INFO_DIAGNOSTICS'); ?></h2></div><div class="xdecaro-card__body"><div class="table-responsive"><table class="table table-sm"><thead><tr><th><?php echo Text::_('COM_XDECARODRAW_CHECK'); ?></th><th><?php echo Text::_('COM_XDECARODRAW_STATUS'); ?></th></tr></thead><tbody><?php foreach ($this->diagnostics as $name => $ok) : ?><tr><th scope="row"><code>#__xdecarodraw_<?php echo $this->escape($name); ?></code></th><td><span class="xdd-status <?php echo $ok ? 'xdd-status--published' : ''; ?>"><?php echo $ok ? Text::_('JYES') : Text::_('JNO'); ?></span></td></tr><?php endforeach; ?><tr><th scope="row"><?php echo Text::_('COM_XDECARODRAW_CORE_API'); ?></th><td><?php echo $this->coreApiAvailable ? Text::_('JYES') : Text::_('JNO'); ?></td></tr><tr><th scope="row"><?php echo Text::_('COM_XDECARODRAW_CORE_CAPABILITIES'); ?></th><td><?php echo $this->coreCapabilityAvailable ? Text::_('JYES') : Text::_('JNO'); ?></td></tr></tbody></table></div></div></section>
</div>
